# Generated by Django 4.2.1 on 2023-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Select a Category'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Eletronics'), ('Home', 'Home'), ('Video Games', 'Video Games'), ('Entertainment', 'Entertainment'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Clothing', 'Clothing'), ('Literature', 'Literature')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6, null=True),
        ),
    ]
