# Generated by Django 4.2.1 on 2023-05-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
