# Generated by Django 4.2.1 on 2023-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
