# Generated by Django 4.2.1 on 2023-06-29 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0003_message_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc1', models.CharField(max_length=60)),
                ('desc2', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='static/finalproject/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='pack',
            name='video',
            field=models.FileField(null=True, upload_to='static/finalproject/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
