# Generated by Django 4.2.1 on 2023-06-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0004_team_delete_video_pack_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
