# Generated by Django 4.2.1 on 2023-06-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0006_alter_team_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
