# Generated by Django 4.2.1 on 2023-06-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0009_alter_pack_desc1_alter_pack_desc2_alter_pack_desc3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='short',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
