# Generated by Django 4.2.1 on 2023-06-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0010_pack_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='fitr',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
