# Generated by Django 4.2.1 on 2023-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_id_alter_post_timestamp_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
