# Generated by Django 4.2.1 on 2023-06-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_followers_post_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='following',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(related_name='subs', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='subbing', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
