# Generated by Django 4.2.1 on 2023-06-11 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(default=None, related_name='subbing', to=settings.AUTH_USER_MODEL),
        ),
    ]
